# Generated by Django 5.0 on 2024-09-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_app', '0004_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
