# Generated by Django 5.0 on 2024-09-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_app', '0005_remove_cartitem_cart_cartitem_email_delete_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
    ]
