# Generated by Django 5.0 on 2024-09-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_app', '0009_alter_cartitem_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
