# Generated by Django 5.0 on 2024-09-30 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_app', '0012_customuser_reset_code_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItem',
            new_name='CartItems',
        ),
    ]
