# Generated by Django 5.0 on 2024-09-30 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_app', '0013_rename_cartitem_cartitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop_app.product')),
            ],
        ),
    ]
