# Generated by Django 5.0 on 2024-09-30 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_app', '0014_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItems',
        ),
    ]
